"""Tabla de lecciones

Revision ID: 60beb63f572c
Revises: 21ccda13c446
Create Date: 2021-12-04 16:49:45.812104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60beb63f572c'
down_revision = '21ccda13c446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    # ### end Alembic commands ###
